let catalog = {
    "data": [
      {
        "productName": "Producto A",
        "category": "Filtro1",
        "price": "30",
        "image": "./img/ubits.png",
        "inventory": 14,
      },
      {
        "productName": "Producto 4",
        "category": "Filtro2",
        "price": "49",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto H",
        "category": "Filtro4",
        "price": "99",
        "image": "./img/ubits.png",
        "inventory": 2,
      },
      {
        "productName": "Producto C",
        "category": "Filtro1",
        "price": "29",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto 100",
        "category": "Filtro3",
        "price": "129",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto 5",
        "category": "Filtro2",
        "price": "89",
        "image": "./img/ubits.png",
        "inventory": 1,
      },
      {
        "productName": "Producto 56",
        "category": "Filtro3",
        "price": "189",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto F",
        "category": "Filtro2",
        "price": "49",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto 56",
        "category": "Filtro3",
        "price": "189",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto F",
        "category": "Filtro2",
        "price": "49",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto 56",
        "category": "Filtro3",
        "price": "189",
        "image": "./img/ubits.png",
        "inventory": 9,
      },
      {
        "productName": "Producto F",
        "category": "Filtro2",
        "price": "49",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto 4",
        "category": "Filtro2",
        "price": "49",
        "image": "./img/ubits.png",
        "inventory": 123,
      },
      {
        "productName": "Producto H",
        "category": "Filtro4",
        "price": "99",
        "image": "./img/ubits.png",
        "inventory": 3,
      },
      {
        "productName": "Producto C",
        "category": "Filtro1",
        "price": "29",
        "image": "./img/ubits.png",
        "inventory": 30,
      },
      {
        "productName": "Producto C",
        "category": "Filtro1",
        "price": "29",
        "image": "./img/ubits.png",
        "inventory": 40,
      },
    ],
  };